global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Backend metrics
  - job_name: "microfrontend-backend"
    static_configs:
      - targets: ["backend:3001"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  # Frontend metrics (if implemented)
  - job_name: "microfrontend-frontend"
    static_configs:
      - targets: ["frontend:3000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # Node.js metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Nginx metrics
  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  # PostgreSQL metrics
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
